In [1]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score
import pickle
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
import string
import pandas as pd 
import pymysql

In [2]:
def read_mysql_table(table, host='localhost', user='root', password='', database='review'):
    # Establish a connection to the MySQL database
    connection = pymysql.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )
    
    # Create a cursor object to execute SQL queries
    cursor = connection.cursor()
    
    query = f"SELECT * FROM {table}"
    cursor.execute(query)
    result = cursor.fetchall()
    
    # Convert the result to a Pandas DataFrame
    df = pd.DataFrame(result)
    
    # Assign column names based on the cursor description
    df.columns = [column[0] for column in cursor.description]
    
    # Close the cursor and the database connection
    cursor.close()
    connection.close()
    
    return df

In [3]:
table_name = 'input_review'
df = read_mysql_table(table_name)
df.head()

   id_review    nama     tanggal review
0         29  slamet  2024-01-10  bagus
1         30  slamet  2024-01-10  jelek
2         31    ardi  2024-01-10   good

In [4]:
# text preprocessing
def preprocess_text(content):
    import nltk
    import re
    nltk.download('stopwords')
    nltk.download('punkt')

    # filtering

    text = re.sub(r'\W', ' ', str(content))
    text = re.sub(r'\s+[a-zA-Z]\s+', ' ', content)
    text = re.sub(r'\^[a-zA-Z]\s+', ' ', content)
    text = re.sub(r'\s+', ' ', content, flags=re.I)
    text = re.sub(r'^b\s+', '', content)

    # case folding
    text = text.lower()

    # Tokenisasi
    tokens = word_tokenize(text)

    # Menghapus stopwords
    stop_words = set(stopwords.words('indonesian'))
    tokens = [word for word in tokens if word.lower() not in stop_words]

    # Menggabungkan kembali tokens menjadi kalimat
    preprocessed_text = ' '.join(tokens)

    return preprocessed_text

# Melakukan preprocessing pada semua ulasan
df['preprocessed_text'] = df['review'].apply(preprocess_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Rama\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Rama\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Rama\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Rama\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Rama\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Rama\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [5]:
ulasan = df['preprocessed_text']

In [6]:
ulasan

0    bagus
1    jelek
2     good
Name: preprocessed_text, dtype: object

In [8]:
# Specify the file path of the pickle file
file_path = 'D:\\Semester 5\\Capstone\\flaks(1)\\flaks\\model\\review.pickle'

# Read the pickle file
with open(file_path, 'rb') as file:
    data_train = pickle.load(file)

In [9]:
data_train

<600x1542 sparse matrix of type '<class 'numpy.float64'>'
	with 5595 stored elements in Compressed Sparse Row format>

In [11]:
# pembuatan vector kata
vectorizer = TfidfVectorizer()
train_vector = vectorizer.fit_transform(data_train)
review2 = ["".join(r) for r in ulasan]

IndexError: Index dimension must be 1 or 2

In [51]:
load_model = pickle.load(open('Model/model_svm.pkl','rb'))

result = []

for test in review2:
    test_data = [str(test)]
    test_vector = vectorizer.transform(test_data)
    vektor_tfidf = test_vector.toarray()

    pred = load_model.predict(vektor_tfidf)
    result.append(pred[0])

c:\Users\rafae\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:348: InconsistentVersionWarning: Trying to unpickle estimator SVC from version 1.2.2 when using version 1.3.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [52]:
result

[5, 5, 5, 5, 5, 5, 3, 3, 3, 5, 5, 5, 5, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3]

In [53]:
from sklearn.utils.multiclass import unique_labels
unique_labels(result)

array([1, 3, 5], dtype=int64)

In [54]:
df['label'] = result

In [55]:
df

,id_review,nama,tanggal,review,preprocessed_text,label
0,121,Suep,2023-12-01,Bagus,bagus,5
1,122,Verza,2023-12-02,Bagus bangett mantappp,bagus bangett mantappp,5
2,123,Rosi,2023-12-03,Bagus,bagus,5
3,124,Tari,2023-12-04,aplikasinya oke bagus bangettt mantapppp,aplikasinya oke bagus bangettt mantapppp,5
4,125,Tarmo,2023-12-05,aplikasinya oke bagus bangettt mantapppp,aplikasinya oke bagus bangettt mantapppp,5
5,126,Nopal,2023-12-06,aplikasinya oke bagus bangettt mantapppp,aplikasinya oke bagus bangettt mantapppp,5
6,127,Reza,2023-12-07,bagus bangettt mantapppp,bagus bangettt mantapppp,3
7,128,Feri,2023-12-08,bagus bangettt mantapppp,bagus bangettt mantapppp,3
8,129,Atha,2023-12-09,bagus bangettt mantapppp,bagus bangettt mantapppp,3
9,130,Nimah,2023-12-10,good,good,5
10,131,Torja,2023-12-11,bagus,bagus,5
11,132,Suni,2023-12-12,bagus,bagus,5
12,133,Yika,2023-12-13,bagus,bagus,5
13,134,Kondor,2023-12-01,jelek banget,jelek banget,1
14,135,Rama,2023-12-02,aplikasi jelek banget,aplikasi jelek banget,1
15,136,Afkar,2023-12-03,aplikasi jelek banget,aplikasi jelek banget,1
16,137,Rokayah,2023-12-04,"sampah, aplikasi jelek banget","sampah , aplikasi jelek banget",1
17,138,Leni,2023-12-01,lumayan sih,lumayan sih,3
18,139,Zen,2023-12-02,lumayan,lumayan,3
19,140,Kori,2023-12-03,lumayan sihh,lumayan sihh,3
20,141,Rizki,2023-12-04,lumayan sihh,lumayan sihh,3
21,142,Maulana,2023-12-05,lumayan sihh,lumayan sihh,3
22,143,Sobri,2023-12-06,lumayan sih,lumayan sih,3
23,144,Durma,2023-12-07,lumayan deh,lumayan deh,3
24,145,Sonya,2023-12-08,lumayan deh,lumayan deh,3

In [56]:
def delete_all_data_from_table(table, host='localhost', user='root', password='', database='review'):
    # Establish a connection to the MySQL database
    connection = pymysql.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )
    
    # Create a cursor object to execute SQL queries
    cursor = connection.cursor()
    
    # Delete all data from the specified table
    query = f"DELETE FROM {table}"
    cursor.execute(query)
    
    # Commit the changes
    connection.commit()
    
    # Close the cursor and the database connection
    cursor.close()
    connection.close()

In [57]:
delete_all_data_from_table('input_review')

In [58]:
def insert_df_into_hasil_model(df, host='localhost', user='root', password='', database='review'):
    # Establish a connection to the MySQL database
    connection = pymysql.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )

    # Create a cursor object to execute SQL queries
    cursor = connection.cursor()

    # Insert each row from the DataFrame into the 'hasil_model' table
    for index, row in df.iterrows():
        query = "INSERT INTO hasil_model (id_review, nama, tanggal, review, label) VALUES (%s, %s, %s, %s, %s)"
        cursor.execute(query, (row['id_review'], row['nama'], row['tanggal'], row['review'], row['label']))

    # Commit the changes
    connection.commit()

    # Close the cursor and the database connection
    cursor.close()
    connection.close()

In [59]:
insert_df_into_hasil_model(df)

In [60]:
table_name = 'hasil_model'
hasil_df = read_mysql_table(table_name)
hasil_df.to_csv('hasil_model2.csv')